config/routes.rb
class AuthenticatedConstraint
  def matches?(request)
    request.session['user_id'].present?
  end
end

Rails.application.routes.draw do
  #mount RailsAdmin::Engine => '/admin', as: 'rails_admin'  　　　devise導入したら使う
  constraints AuthenticatedConstraint.new do
    root to: 'projects#index', as: :user_root
  end
  
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'sample_login', to: 'sessions#sample_login'
  
  get 'signup', to: 'users#new'
  resources :users do
    member do
      get :followings
      get :followers
    end
  end
  
  #get 'projects/category', to: 'projects#category_index'

  #get 'projects/category/language', to: 'projects#category_index'
  #get 'projects/category/club', to: 'projects#category_index'
  #get 'projects/category/event', to: 'projects#category_index'
  #get 'projects/category/study', to: 'projects#category_index'
  #get 'projects/category/job', to: 'projects#category_index'
  #get 'projects/category/debate', to: 'projects#category_index'
  #get 'projects/category/business', to: 'projects#category_index'
  #get 'projects/category/sports', to: 'projects#category_index'
  #get 'projects/category/travel', to: 'projects#category_index'
  #get 'projects/category/hobby', to: 'projects#category_index'
  #get 'projects/category/music', to: 'projects#category_index'
  #get 'projects/category/picture', to: 'projects#category_index'
  #get 'projects/category/art', to: 'projects#category_index'
  #get 'projects/category/game', to: 'projects#category_index'
  #get 'projects/category/technology', to: 'projects#category_index'
  #get 'projects/category/others', to: 'projects#category_index'
  resources :projects, only: [:index, :show, :new, :create, :update] do
    member do
      put :call_off
      resources :comment_to_projects, only: [:index, :create, :edit, :update, :destroy]
    end
    collection do
      get 'all', to: 'projects#all_projects'
      get 'fresh', to: 'projects#fresh_projects'
      get 'popular', to: 'projects#popular_projects'
      get 'closing_soon', to: 'projects#closing_soon_projects'
      get 'category/:id', to: 'projects#category_projects'
      get 'search', to: 'projects#searched_projects'
    end
  end
  resources :user_relationships, only: [:create, :destroy]
  resources :applikations, only: [:create, :update] do
    member do
      put :cancel
      put :rejoin
    end
  end
  resources :project_favorites, only: [:create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  before_save :find_or_create_university
  
  
  belongs_to :university, optional: true
  attr_accessor :university_name
  
  
  validates :name, presence: true,
                   length: { maximum: 30 },
                   uniqueness: true
  validates :email, presence: true,
                    length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  validates :profile, length: { maximum: 255 }
  validates :password, length: { minimum: 8 }, on: :create
  validates :password, length: {minimum: 8}, on: :update, allow_blank: true
  validates :university_name, presence: true, on: :create
  validates :university_name, presence: true, on: :update, allow_blank: true
  
  
  has_secure_passwords
  
  
  has_many :projects, dependent: :destroy
  has_many :user_relationships, dependent: :destroy
  has_many :followings, through: :user_relationships, source: :follow, dependent: :destroy
  has_many :reverses_of_user_relationship, class_name: 'UserRelationship', foreign_key: 'follow_id', dependent: :destroy
  has_many :followers, through: :reverses_of_user_relationship, source: :user, dependent: :destroy
  has_many :project_favorites, dependent: :destroy
  has_many :likes, through: :project_favorites, source: :project, dependent: :destroy
  has_many :applikations, dependent: :destroy
  has_many :participatings, through: :applikations, source: :project, dependent: :destroy
  has_many :comment_to_projects, dependent: :destroy
  
  
  mount_uploader :image, ImageUploader
  
  
  #大学名検索&登録
  def find_or_create_university
    if university_name.present?
      self.university = University.find_or_create_by!(name: university_name)
    end
  end
  
  
  #フォロー機能
  def follow(other_user)
    unless self == other_user
      self.user_relationships.find_or_create_by(follow_id: other_user.id)
    end
  end
  
  def unfollow(other_user)
    user_relationship = self.user_relationships.find_by(follow_id: other_user.id)
    user_relationship.destroy if user_relationship
  end
  
  def following?(other_user)
    self.followings.include?(other_user)
  end
  
  
  #お気に入り機能
  def like(project)
    self.project_favorites.find_or_create_by(project_id: project.id)
  end
  
  def unlike(project)
    project_favorite = self.project_favorites.find_by(project_id: project.id)
    project_favorite.destroy if project_favorite
  end
  
  def liking?(project)
    self.likes.include?(project)
  end
  
  
  #プロジェクト参加/キャンセル機能
  def participate(project)
    self.applikations.find_or_create_by(project_id: project.id)
  end
  
  def cancel(project)
    applikation = self.applikations.find_by(project_id: project.id)
    applikation.update(cancel: true, canceled_at: DateTime.now) if applikation
  end
  
  def rejoin(project)
    applikation = self.applikations.find_by(project_id: project.id)
    applikation.update(cancel: false, canceled_at: nil) if applikation.cancel = true
  end
  
  def participating?(project)
    self.participatings.include?(project)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show, :edit, :update, :destroy]
  before_action :set_search, only: [:index, :show, :edit, :followings, :followers, :likes, :participatings]
  before_action :correct_user, only: [:edit, :destroy]
  
  
  def index
    @users = User.all.page(params[:page])
  end

  def show
    @user = User.find(params[:id])
    @not_cancelled_paticipatings = Project.joins(:reverses_of_applikation).where(applikations: { user_id: @user.id, cancel: false }).group(:id)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      login(@user.email, @user.password)
      flash[:success] = 'ユーザーを登録しました。'
      redirect_to root_url
    else
      flash.now[:danger] = 'ユーザーの登録に失敗しました。'
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    
    if @user.update(user_params)
      flash[:success] = 'ユーザー情報を更新しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザー情報を更新できませんでした。'
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    
    flash[:success] = 'アカウントを削除しました。'
    redirect_to root_url
  end
  
  def followings
    @user = User.find(params[:id])
    @followings = @user.followings.page(params[:page])
  end
  
  def followers
    @user = User.find(params[:id])
    @followers = @user.followers.page(params[:page])
  end
  
  def likes
    @user = User.find(params[:id])
    @likes = @user.likes.page(params[:page])
  end
  
  def participatings
    @user = User.find(params[:id])
    @participatings = @user.participatings.page(params[:page])
  end
  
  
  private
  
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :university_name, :image, :profile)
    end
end

app/views/users/_form_for_profile.html.erb
<%= form_for(@user) do |f| %>
  <div class="form-group">
    <%= f.label :profile, 'プロフィール' %>
    <%= f.text_area :profile, placeholder: 'プロフィールを入力してください', class: 'form-control', rows: 5 %>
  </div>
<% end %>

app/views/users/_users.html.erb
<% if users.any? %>
  <ul class="media-list">
    <% users.each do |user| %>
      <li class="media">
        <div class="media-left">
          <img class="media-object img-rounded" src="/assets/f_f_object_115_s64_f_object_115_0bg.png" alt="user_icon">
        </div>
        <div class="media-body">
          <div>
            <%= link_to user.name, user_path(user) %>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/users/edit.html.erb
<div class="text-center user_title">
  <h1>ユーザー編集</h1>
</div>

<div class="row">
  <div class="col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3">
    
    <%= form_for(@user) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      
      <div class="form-group">
        <div class="text-center">
          <div id="img_field" class="user_img_edit" onClick="$('#file').click()">
            <% if @user.image.present? %>
              <%= image_tag @user.image.to_s, class: 'user_icon_md img-rounded', width: '130', height: '130' %>
            <% else %>
              <img class="user_icon img-rounded" src="/assets/f_f_object_115_s128_f_object_115_0bg.png">
            <% end %>
            <i class="fas fa-camera fa-3x"></i>
          </div>
        </div>
        <%= f.file_field :image, class: 'form-control', style: "display:none;", id: "file" %>
      </div>
      
      <div class="form-group">
        <%= f.label :name, 'ユーザー名(サイト上で表示されます)' %>
        <%= f.text_field :name, placeholder: '30文字以内', class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :profile, 'プロフィール' %>
        <%= f.text_area :profile, placeholder: 'プロフィールを入力してください', class: 'form-control', rows: 5 %>
      </div>
      
      <div class="user_edit_buttons">
        <%= link_to 'キャンセル', user_path(@user), class: 'btn btn-default col-xs-12 col-sm-5' %>
        <%= f.submit '更新する', class: 'btn btn-primary col-xs-12 col-sm-5 col-sm-offset-2' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/followers.html.erb
<div class="followers_header text-center col-md-12">
  <h1>フォロワー</h1>
</div>
<div class="col-md-12">
  <% if @followers.count == 0 %>
    <p class="col-md-12">フォロワーはいません。</p>
  <% else %>
    <%= render 'users/users', users: @followers %>
  <% end %>
</div>

app/views/users/followings.html.erb
<div class="followings_header text-center col-md-12">
  <h1>フォロー</h1>
</div>
<div class="col-md-12">
  <% if @followings.count == 0 %>
    <p class="col-md-12">フォローしているユーザーはいません。</p>
  <% else %>
    <%= render 'users/users', users: @followings %>
  <% end %>
</div>

app/views/users/index.html.erb
<%= render 'users', users: @users %>

app/views/users/new.html.erb
<div class="text-center">
  <h1>ユーザー登録</h1>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    
    <%= form_for(@user) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      
      <div class="form-group">
        <%= f.label :user_name, 'ユーザー名(サイト上で表示されます)' %>
        <%= f.text_field :name, placeholder: '30文字以内', class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :email, 'メールアドレス' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :password, 'パスワード' %>
        <%= f.password_field :password, placeholder: '8文字以上', class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :password_confirmation, 'パスワード(確認)' %>
        <%= f.password_field :password_confirmation, placeholder: 'もう一度入力してください', class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :university_name, '大学名' %>
        <%= f.text_field :university_name, class: 'form-control' %>
      </div>
      
      <%= f.submit '登録', class: "btn btn-primary btn-block" %>
    <% end %>
    <p><%= link_to 'ログインはこちら', login_path %></p>
  </div>
</div>

app/views/users/profile.html.erb
<%= form_for(@user) do |f| %>
  <div class="form-group">
    <%= f.label :profile, 'プロフィール' %>
    <%= f.text_area :profile, placeholder: 'プロフィールを入力してください', class: 'form-control', rows: 5 %>
  </div>
<% end %>

app/views/users/show.html.erb
<div class="text-center user_title">
  <% if current_user == @user %>
    <h1>マイページ</h1>
  <% else %>
    <h1>プロフィール</h1>
  <% end %>
</div>

<% if current_user == @user %>
  <div class="col-xs-12">
    <div class="col-md-2 col-md-offset-7">
      <div class="text-right">
        <%= link_to '編集する', edit_user_path %>
      </div>
    </div>
  </div>
<% end %>

<div class="text-center">
  <div class="user_img">
    <%# アイコン画像　正方形　角丸 %>
    <% if @user.image.present? %>
      <%= image_tag(@user.image.to_s, class: 'user_icon-md img-rounded', width: '130', height: '130') %>
    <% else %>
      <img class="user_icon img-rounded" src="../assets/f_f_object_115_s128_f_object_115_0bg.png">
    <% end %>
  </div>
  <div class="user_name">
    <h2><%= @user.name %></h2>
  </div>
</div>

<%# ユーザープロフィール %>
<% if @user.profile %>
  <div class="user_profile col-xs-12 col-sm-8 col-sm-offset-2 col-md-8 col-md-offset-2">
    <p><%= simple_format(text_url_to_link(h(@user.profile).html_safe)) %></p>
  </div>
<% end %>

<div class="col-md-12">
  <div class="col-xs-6 col-md-3 col-md-offset-3">
    <div class="text-center">
      <h4><%= link_to 'フォロー', followings_user_path(@user) %></h4>
      <h4><%= link_to @user.followings.count, followings_user_path(@user) %></h4>
    </div>
  </div>
  <div class="col-xs-6 col-md-3">
    <div class="text-center">
      <h4><%= link_to 'フォロワー', followers_user_path(@user) %></h4>
      <h4><%= link_to @user.followers.count, followers_user_path(@user) %></h4>
    </div>
  </div>
</div>


<div class="follow_unfollow col-xs-8 col-xs-offset-2 col-sm-4 col-sm-offset-4 col-md-2 col-md-offset-5">
  <%= render 'user_relationships/follow_button', user: @user %>
</div>


<div>
  <% if current_user == @user %>
    <div class="user_tabs col-xs-12">
      <ul class="nav nav-tabs nav-justified">
        <li class="nav-item col-xs-4">
          <a class="nav-link active" href="#participating_projects" data-toggle="tab">参加したプロジェクト <span class="badge tabs_badge"><%= @not_cancelled_paticipatings.length %></a>
        </li>
        <li class="nav-item col-xs-4">
          <a class="nav-link" href="#posted_projects">投稿したプロジェクト <span class="badge tabs_badge"><%= @user.projects.count %></span></a>
        </li>
        <li class="nav-item col-xs-4">
          <a class="nav-link" href="#liked_projects">いいねしたプロジェクト <span class="badge tabs_badge"><%= @user.likes.count %></span></a>
        </li>
      </ul>
      <div class="tab-content">
        <div id="participating_projects" class="tab-pane active">
          <% if @not_cancelled_paticipatings.present? %>
            <%= render 'projects/projects', projects: @not_cancelled_paticipatings.order(created_at: :DESC) %>
          <% else %>
            <p class="no_not_canceled_participatings">参加したプロジェクトはまだありません。</p>
          <% end %>
        </div>
        <div id="posted_projects" class="tab-pane">
          <% if current_user.projects.present? %>
            <%= render 'projects/projects', projects: current_user.projects.order(created_at: :DESC) %>
          <% else %>
            <p class="no_posted_projects">投稿したプロジェクトはまだありません。</p>
          <% end %>
        </div>
        <div id="liked_projects" class="tab-pane">
          <% if current_user.likes.present? %>
            <%= render 'projects/projects', projects: current_user.likes.order(created_at: :DESC) %>
          <% else %>
            <p class="no_liked_projects">いいねしたプロジェクトはまだありません。</p>
          <% end %>
        </div>
      </div>
    </div>
  <% else %>
    <div class="otheruser_posted_projects col-xs-12">
      <h4 class="col-xs-12"><%= @user.name %>さんが投稿したプロジェクト</h4>
      <% if @user.projects.present? %>
        <%= render 'projects/projects', projects: @user.projects.order(created_at: :DESC) %>
      <% else %>
        <p class="no_otheruser_posted_projects col-xs-12">このユーザーが投稿したプロジェクトはまだありません。</p>
      <% end %>
    </div>
  <% end %>
</div>