config/routes.rb
class AuthenticatedConstraint
  def matches?(request)
    request.session['user_id'].present?
  end
end

Rails.application.routes.draw do
  #mount RailsAdmin::Engine => '/admin', as: 'rails_admin'  　　　devise導入したら使う
  constraints AuthenticatedConstraint.new do
    root to: 'projects#index', as: :user_root
  end
  
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'sample_login', to: 'sessions#sample_login'
  
  get 'signup', to: 'users#new'
  resources :users do
    member do
      get :followings
      get :followers
    end
  end
  
  #get 'projects/category', to: 'projects#category_index'

  #get 'projects/category/language', to: 'projects#category_index'
  #get 'projects/category/club', to: 'projects#category_index'
  #get 'projects/category/event', to: 'projects#category_index'
  #get 'projects/category/study', to: 'projects#category_index'
  #get 'projects/category/job', to: 'projects#category_index'
  #get 'projects/category/debate', to: 'projects#category_index'
  #get 'projects/category/business', to: 'projects#category_index'
  #get 'projects/category/sports', to: 'projects#category_index'
  #get 'projects/category/travel', to: 'projects#category_index'
  #get 'projects/category/hobby', to: 'projects#category_index'
  #get 'projects/category/music', to: 'projects#category_index'
  #get 'projects/category/picture', to: 'projects#category_index'
  #get 'projects/category/art', to: 'projects#category_index'
  #get 'projects/category/game', to: 'projects#category_index'
  #get 'projects/category/technology', to: 'projects#category_index'
  #get 'projects/category/others', to: 'projects#category_index'
  resources :projects, only: [:index, :show, :new, :create, :update] do
    member do
      put :call_off
      resources :comment_to_projects, only: [:index, :create, :edit, :update, :destroy]
    end
    collection do
      get 'all', to: 'projects#all_projects'
      get 'fresh', to: 'projects#fresh_projects'
      get 'popular', to: 'projects#popular_projects'
      get 'closing_soon', to: 'projects#closing_soon_projects'
      get 'category/:id', to: 'projects#category_projects'
      get 'search', to: 'projects#searched_projects'
    end
  end
  resources :user_relationships, only: [:create, :destroy]
  resources :applikations, only: [:create, :update] do
    member do
      put :cancel
      put :rejoin
    end
  end
  resources :project_favorites, only: [:create, :destroy]
end

app/models/project.rb
class Project < ApplicationRecord
  include SessionsHelper
  
  belongs_to :user
  belongs_to :project_category
  
  validates :title, presence: true,
                    length: { maximum: 40 }
  validates :content, presence: true,
                      length: { maximum: 1000 }
  validates :deadline, presence: true
  validate :deadline_cannot_be_in_the_past
  validates :recruitment_numbers, presence: true
  
  has_many :reverses_of_project_favorite, class_name: 'Project_favorite', foreign_key: 'project_id', dependent: :destroy
  has_many :liked_users, through: :reverses_of_project_favorite, source: :user, dependent: :destroy
  has_many :comment_to_projects, dependent: :destroy
  has_many :reverses_of_applikation, class_name: 'Applikation', foreign_key: 'project_id', dependent: :destroy
  has_many :participants, through: :reverses_of_applikation, source: :user, dependent: :destroy
  
  
  mount_uploader :image, ImageUploader  #carrierwave
  

  def deadline_cannot_be_in_the_past
    if deadline.present? && deadline.past?
      errors.add(:deadline, "can not specify your past date as your deadline.")
    end
  end
  
  #def self.get_canceled_participants_in(project)
  #  User.joins(:applikations).includes(:applikations).where(applikations: { project_id: project.id, cancel: true })
  #end
  
  def get_not_canceled_participants
    User.joins(:applikations).includes(:applikations).where(applikations: { project_id: self.id, cancel: false }).order("applikations.updated_at ASC")
  end
  
  def get_canceled_participants
    User.joins(:applikations).includes(:applikations).where(applikations: { project_id: self.id, cancel: true }).order("applikations.canceled_at ASC")
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :require_user_logged_in
  before_action :set_search
  
  def index
    @all_projects = university_projects
    @fresh_projects = university_projects.where(deadline: DateTime.now..DateTime::Infinity.new, call_off: false, created_at: 1.week.ago..DateTime.now)
    @popular_projects = university_projects.joins(:reverses_of_applikation).where(deadline: DateTime.now..DateTime::Infinity.new, call_off: false).merge(Applikation.where(cancel: false)).group(:id).having('count(*) >= 10')
    @closing_soon_projects = university_projects.where(call_off: false, deadline: DateTime.now..5.days.since)
    #@default_project_image_id = project.project_category_id
  end

  def show
    @project = Project.find(params[:id])
    @comment_to_projects = CommentToProject.all
    @comment_to_project = CommentToProject.new
    #@not_canceled_participants = User.joins(:applikations).includes(:applikations).where(applikations: { project_id: @project.id, cancel: false })
    @not_canceled_participants = @project.get_not_canceled_participants
    #@canceled_participants = User.joins(:applikations).includes(:applikations).where(applikations: { project_id: @project.id, cancel: true })
    @canceled_participants = @project.get_canceled_participants
    #@default_project_image_id = @project.project_category_id
    @close_when_reaching_recruitment_numbers = @project.set_the_maximum && (@not_canceled_participants.length >= @project.recruitment_numbers)
  end

  def new
    @project = Project.new
  end

  def create
    @project = current_user.projects.build(project_params)
    
    if @project.save
      flash[:success] = 'プロジェクトを投稿しました。'
      redirect_to @project
    else
      flash.now[:danger] = 'プロジェクトを投稿できませんでした。'
      render :new
    end
  end
  
  def update
    if @project.update(project_params)
      flash[:success] = 'プロジェクトを中止しました。'
      redirect_to @project
    end
  end
  
  def call_off
    @project = Project.find(params[:id])
    @project.update(call_off: true)
    redirect_to @project
  end
  
  def liked_users
    @project = Project.find(params[:id])
    @liked_users = @project.liked_users.page(params[:page])
    counts(@project)
  end
  
  def participants
    @project = Project.find(params[:id])
    @participants = @project.participants.page(params[:page])
    count(@project)
  end
  
  def university_projects
      University.find_by(id: current_user.university_id).projects.order(created_at: :DESC).page(params[:page]).per(20)
  end
  
  def all_projects
    @all_projects = university_projects
  end
  
  def fresh_projects
    @fresh_projects = university_projects.where(deadline: DateTime.now..DateTime::Infinity.new, call_off: false, created_at: 1.week.ago..DateTime.now)
  end
  
  def popular_projects
    @popular_projects = university_projects.joins(:reverses_of_applikation).where(deadline: DateTime.now..DateTime::Infinity.new, call_off: false).merge(Applikation.where(cancel: false)).group(:id).having('count(*) >= 10')
  end
  
  def closing_soon_projects
    @closing_soon_projects = university_projects.where(call_off: false, deadline: DateTime.now..5.days.since)
  end
  
  def category_projects
    @category_projects = university_projects.joins(:project_category).where(project_category_id: params[:id])
    @category_name = ProjectCategory.find_by(id: params[:id]).name
  end
  
  def searched_projects
    @searched_projects = @search.result(distinct: true)
  end
  
  
  
  
  private
    def project_params
      params.require(:project).permit(:title, :content, :project_category_id, :recruitment_numbers, :all_or_nothing, :set_the_maximum, :deadline, :image, :call_off)
    end
end

app/views/projects/_call_off_button.html.erb
<% if current_user == @project.user %>
  <% unless @project.call_off || @project.deadline.past? %>
    <%= link_to 'このプロジェクトを中止する', call_off_project_path(@project), method: :put, data: { confirm: "一度中止すると募集を再開することはできません。本当に中止しますか？" }, class: 'btn btn-danger btn-block' %>
  <% end %>
<% end %>

app/views/projects/_progress-bar.html.erb
<%# 募集人数に対する現在の参加者数の達成度 %>
<% achievement_progress = (project.reverses_of_applikation.where(cancel: false).count.to_f / project.recruitment_numbers.to_f * 100).round %>



<div class="progress">
  <% if project.reverses_of_applikation.where(cancel: false).count.to_f / project.recruitment_numbers.to_f * 100 < 25 %>
    <div id="achievement_progress" class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: <%= achievement_progress %>%;">
      <%= achievement_progress %>%
    </div>
  <% elsif project.reverses_of_applikation.where(cancel: false).count.to_f / project.recruitment_numbers.to_f * 100 < 50 %>
    <div id="achievement_progress" class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: <%= achievement_progress %>%;">
      <%= achievement_progress %>%
    </div>
  <% elsif project.reverses_of_applikation.where(cancel: false).count.to_f / project.recruitment_numbers.to_f * 100 < 75 %>
    <div id="achievement_progress" class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: <%= achievement_progress %>%;">
      <%= achievement_progress %>%
    </div>
  <% else %>
    <div id="achievement_progress" class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: <%= achievement_progress %>%;">
      <%= achievement_progress %>%
    </div>
  <% end %>
</div>

app/views/projects/_project_image.html.erb
<% if @project.image.present? %>
  <%= image_tag @project.image.to_s, class: 'project_img img-responsive' %>
<% elsif @project.project_category.name == '' %>
  <img class="project_img" src="/assets/default_project_image_<%= @default_project_image_id %>" %>
  <%#<img class="project_img img-responsive" src="../assets/default.png">%>
<% end %>

app/views/projects/_project_result.html.erb
<% if @project.call_off %>
  <p><span class="label label-danger col-xs-12">このプロジェクトは中止されました。</span></p>
<% elsif @close_when_reaching_recruitment_numbers %>
  <p><span class="label label-danger col-xs-12">参加者数が定員に達したため、募集が締め切られました。</span></p>
<% elsif @project.deadline.past? && (@not_canceled_participants.length < @project.recruitment_numbers) %>
  <p><span class="label label-danger col-xs-12">このプロジェクトは開催されません。</span></p>
<% elsif @project.deadline.past? %>
  <p><span class="label label-danger col-xs-12">このプロジェクトの募集は終了しました。</span></p>
<% end %>

app/views/projects/_projects.html.erb
<% if projects.any? %>
  <% projects.each do |project| %>
    <div class="col-xs-12 col-sm-4 col-md-3">
      <div class="thumbnail">
        <div class="thumbnail_img">
          <a href="/projects/<%= project.id %>">
            <% unless project.image.blank? %>
              <img class="thumbnail_project_img img-responsive" src="<%= project.image %>">
            <% else %>
              <%#<img class="thumbnail_project_img img-responsive" src="../assets/default.png">    カテゴリーごとにデフォルトの画像を変える%>
            <% end %>
            <%= render 'projects/ribbon', project: project %>
          </a>
        </div>
        <div class="caption">
          <div class="thumbnail_project_title">
            <h5><%= link_to project.title.truncate(34), project_path(project) %></h5>
          </div>
          <div class="row">
            <div class="col-lg-6">
              <p><i class="fas fa-user"></i> <%= link_to project.user.name.truncate(11), user_path(project.user) %></p>
            </div>
            <div class="col-lg-6">
              <p><i class="fas fa-tag"></i> <%= project.project_category.name.truncate(5) %></p>
            </div>
          </div>
          <p><i class="far fa-clock"></i>
            <% if ((project.deadline - DateTime.now) / 24 / 60 / 60).floor < 0 || project.call_off %>
              終了
            <% elsif ((project.deadline - DateTime.now) / 60 / 60).floor < 1 %>
              あと<%= ((project.deadline - DateTime.now) / 60).floor %>分
            <% elsif ((project.deadline - DateTime.now) / 24 / 60 / 60).floor < 1 %>
              あと<%= ((project.deadline - DateTime.now) / 60 / 60).floor %>時間
            <% else %>
              あと<%= ((project.deadline - DateTime.now) / 24 / 60 / 60).floor %>日
            <% end %>
          </p>
          <p>募集人数 <%= project.recruitment_numbers %>人</p>
          <p>現在参加者 <%= project.reverses_of_applikation.where(cancel: false).count %>人</p>
          <%= render 'projects/progress-bar', project: project %>
        </div>
      </div>
    </div>
  <% end %>
<% end %>
<%# 画像かタイトルをクリックすればそのプロジェクトの詳細ページへ飛ぶようにする %>
<%# プログレスバーや数字はJSでリアルタイムに動かす %>
<%# サムネイルの高さ合わせる(比率は変えたくない) %>
<%# 「カテゴリー」をクリックすると、カテゴリー別のプロジェクト一覧 %>

app/views/projects/all_projects.html.erb
<div class="row university_projects col-xs-12">
    <h1 class="col-md-7"><%= current_user.university.name %>のプロジェクト</h1>
</div>
<div class="row all_projects">
    <div class="projects_type_header col-xs-12">
        <div class="projects_type col-xs-12">
            <h4>すべてのプロジェクト <span class="badge projects_count_badge"><%= @all_projects.count %></span></h4>
        </div>
    </div>
    <div class="project_type_body col-xs-12">
      <%= render 'projects/projects', projects: @all_projects %>
      <div class="text-center col-xs-12">
          <%= paginate @all_projects %>
      </div>
    </div>
</div>

app/views/projects/category_projects.html.erb
<div class="row university_projects col-xs-12">
    <h1 class="col-md-6"><%= current_user.university.name %>のプロジェクト</h1>
</div>
<div class="row all_projects">
    <div class="projects_type_header col-xs-12">
        <div class="projects_type col-xs-12">
            <h4>カテゴリー： "<%= @category_name %>" のプロジェクト <span class="badge projects_count_badge"><%= @category_projects.count %></span></h4>
        </div>
    </div>
    <div class="project_type_body col-xs-12">
      <%= render 'projects/projects', projects: @category_projects %>
      <%= paginate @category_projects %>
    </div>
</div>

app/views/projects/closing_soon_projects.html.erb
<div class="row university_projects col-xs-12">
    <h1 class="col-md-7"><%= current_user.university.name %>のプロジェクト</h1>
</div>
<div class="row closing_soon_projects">
    <div class="projects_type_header col-xs-12">
        <div class="projects_type col-xs-12">
            <h4>締切間近のプロジェクト <span class="badge projects_count_badge"><%= @closing_soon_projects.count %></span></h4>
        </div>
    </div>
    <div class="project_type_body col-xs-12">
      <%= render 'projects/projects', projects: @closing_soon_projects %>
      <div class="text-center col-xs-12">
          <%= paginate @closing_soon_projects %>
      </div>
    </div>
</div>

app/views/projects/fresh_projects.html.erb
<div class="row university_projects col-xs-12">
    <h1 class="col-md-7"><%= current_user.university.name %>のプロジェクト</h1>
</div>
<div class="row fresh_projects">
    <div class="projects_type_header col-xs-12">
        <div class="projects_type col-xs-12">
            <h4>新着のプロジェクト <span class="badge projects_count_badge"><%= @fresh_projects.count %></span></h4>
        </div>
    </div>
    <div class="project_type_body col-xs-12">
      <%= render 'projects/projects', projects: @fresh_projects %>
      <div class="text-center col-xs-12">
          <%= paginate @fresh_projects %>
      </div>
    </div>
</div>

app/views/projects/index.html.erb
<div class="row university_projects">
    <div class="university_projects_header col-xs-12">
        <h1 class="col-xs-12 col-sm-8 col-md-7"><%= current_user.university.name %>のプロジェクト</h1>
        <div class="see_all col-xs-12 col-sm-2 col-md-2">
            <%= link_to 'すべて見る', all_projects_path, class: "btn btn-primary" %>
        </div>
    </div>
</div>
<div class="row fresh_projects">
    <div class="projects_type_header col-xs-12">
        <div class="projects_type col-xs-9 col-sm-5 col-md-3">
            <h4>新着のプロジェクト</h4>
        </div>
        <div class="col-xs-3 col-sm-2 col-md-2">
            <%= link_to 'もっと見る', fresh_projects_path, class: "see_more btn btn-default btn-sm" %>
        </div>
    </div>
    <div class="projects_type_body col-xs-12">
        <%= render 'projects/projects', projects: @fresh_projects.limit(8) %>
    </div>
</div>
<div class="row popular_projects">
    <div class="projects_type_header col-md-12">
        <div class="projects_type col-xs-9 col-sm-5 col-md-3">
            <h4>人気のプロジェクト</h4>
        </div>
        <div class="col-xs-3 col-sm-2 col-md-2">
            <%= link_to 'もっと見る', popular_projects_path, class: "see_more btn btn-default btn-sm" %>
        </div>
    </div>
    <div class="projects_type_body col-xs-12">
        <%= render 'projects/projects', projects: @popular_projects.limit(8) %>
    </div>
</div>
<div class="row closing_soon_projects">
    <div class="projects_type_header col-md-12">
        <div class="projects_type col-xs-9 col-sm-5 col-md-3">
            <h4>締切間近のプロジェクト</h4>
        </div>
        <div class="col-xs-3 col-sm-2 col-md-2">
            <%= link_to 'もっと見る', closing_soon_projects_path, class: "see_more btn btn-default btn-sm" %>
        </div>
    </div>
    <div class="projects_type_body col-xs-12">
        <%= render 'projects/projects', projects: @closing_soon_projects.limit(8) %>
    </div>
</div>

app/views/projects/new.html.erb
<div class="text-center">
  <h1>プロジェクトをはじめる</h1>
</div>

<div class="row">
  <div class="form_for_project col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3">
    
    <%= form_for(@project) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      
      <div class="form-group">
        <%= f.label :title, 'タイトル' %>
        <%= f.text_field :title, placeholder: '40文字以内', class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :content, '活動内容' %>
        <%= f.text_area :content, placeholder: '何をするのか、開催日、活動場所など、プロジェクトについての説明を書いてください', class: 'form-control', rows: 10 %>
      </div>
      
      <div class="form-group">
        <%= f.label :project_category_id, 'カテゴリー' %>
        <%= f.collection_select :project_category_id, ProjectCategory.all, :id, :name, { prompt: '選択してください'}, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :recruitment_numbers, '募集人数' %>
        <%= f.number_field :recruitment_numbers, min: 1, class: 'form-control' %>
        <%= f.check_box :all_or_nothing %> 募集人数に達しなければ開催しない<br>
        <%= f.check_box :set_the_maximum %> 募集人数に達し次第締め切る
      </div>
      
      <div class="form-group">
        <%= f.label :deadline, '締切' %>
        <%= f.text_field :deadline, class: 'form-control datepicker' %>
      </div>
      
      <div class="form-group">
        <%= f.label :image, '画像' %>
        <%= f.file_field :image, class: 'form-control' %>
      </div>
      
      <%= f.submit '投稿する', class: "btn btn-primary btn-block" %>
    <% end %>
  </div>
</div>

app/views/projects/popular_projects.html.erb
<div class="row university_projects col-xs-12">
    <h1 class="col-md-7"><%= current_user.university.name %>のプロジェクト</h1>
</div>
<div class="row popular_projects">
    <div class="projects_type_header col-xs-12">
        <div class="projects_type col-xs-12">
            <h4>人気のプロジェクト <span class="badge projects_count_badge"><%= @popular_projects.length %></span></h4>
        </div>
    </div>
    <div class="project_type_body col-xs-12">
      <%= render 'projects/projects', projects: @popular_projects %>
      <div class="text-center col-xs-12">
          <%= paginate @popular_projects %>
      </div>
    </div>
</div>

app/views/projects/searched_projects.html.erb
<div class="row university_projects">
    <div class="projects_type_header col-md-12">
        <div class="col-md-12">
            <h1>キーワード: "<%= params[:q][:title_or_content_or_project_category_name_cont] %>"を含むプロジェクト</h1>
        </div>
    </div>
</div>
<div class="row searched_projects">
    <div class="projects_type_header col-md-12">
        <% unless @searched_projects.count == 0 %>
            <div class="projects_type col-md-3">
                <h4>すべてのプロジェクト (<%= @searched_projects.count %>件)</h4>
            </div>
        <% end %>
    </div>
    <div class="project_type_body col-md-12">
        <% if @searched_projects.count == 0 %>
            <p class="col-md-12">"<%= params[:q][:title_or_content_or_project_category_name_cont] %>"を含むプロジェクトは見つかりませんでした</p>
        <% else %>
            <%= render 'projects/projects', projects: @searched_projects %>
            <%= paginate @searched_projects %>
        <% end %>
    </div>
</div>

app/views/projects/show.html.erb
<%# プロジェクトが中止されていたら/募集が終了していたらここに表示する %>
<div class="project_result col-xs-12">
  <%= render 'projects/project_result' %>
</div>
<%# ----------------------------------------------------------------- %>

<div class="project_title col-md-12">
  <h1><%= @project.title %></h1>
</div>
<div class="text-right col-md-12">
  <%= render 'project_favorites/like_button', project_id: @project.id %>
</div>
<div class="col-md-7">
  <div class="project_detail_img">
    <% if @project.image.present? %>
      <%= image_tag @project.image.to_s, class: 'project_img img-responsive' %>
    <% else %>
      <%#<img class="project_img img-responsive" src="../assets/default.png">%>
    <% end %>
  </div>
  <div class="twitter for-md-screen">
    <a href="https://twitter.com/share?ref_src=twsrc%5Etfw" class="twitter-share-button" data-show-count="false" data-text="Matchaでおもしろいプロジェクトを見つけたよ!" data-size="large">Tweet</a>
    <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
    <p class="twitter-share-message">Twitterでシェアしよう!</p>
  </div>
</div>
<div class="project_details col-md-5">
  <div class="project_category">
    <i class="fas fa-tag"></i> <%= @project.project_category.name %>
    <%# <i class="fas fa-tag"></i> <%= link_to @project.project_category.name, '/projects/@project.project_category.name'  //カテゴリー別の一覧に飛ばしたい%> 
  </div>
  <div class="project_recruitment_numbers row">
    <h2 class="col-xs-7">募集人数</h2>
    <h2 class="text-right col-xs-5"><%= @project.recruitment_numbers %>人</h2>
  </div>
  <div class="project_participants_number row">
    <h2 class="col-xs-7">現在参加者</h2>
    <h2 class="text-right col-xs-5"><%= @not_canceled_participants.length %>人</h2>
  </div>
  <div class="project_deadline row">
    <h2 class="col-xs-3">締切</h2>
    <h2 class="text-right col-xs-9"><%= @project.deadline.strftime("%Y年 %m月 %d日 %H:%M") %></h2>
  </div>
  <div class="media project_owner">
    <a class="media-left">
      <% if @project.user.image.present? %>
        <%= image_tag @project.user.image.to_s, class: 'user_icon img-rounded', width: "65", height: "65" %>
      <% else %>
        <img class="media-object img-rounded" src="../assets/f_f_object_115_s64_f_object_115_0bg.png">
      <% end %>
    </a>
    <div class="media-body">
      <h3><%= link_to @project.user.name, user_path(@project.user) %></h3>
    </div>
  </div>
  <% if @project.all_or_nothing %>
    <p class="all_or_nothing_message">※このプロジェクトは参加者が募集人数に達しなければ開催されません。</p>
  <% end %>
  <% if @project.set_the_maximum %>
    <p class="set_the_maximum_message">※このプロジェクトは参加者が募集人数に達し次第募集が締め切られます。キャンセルが出た場合、募集が再開されます。</p>
  <% end %>
  <% if current_user == @project.user %>
    <%= render 'projects/call_off_button', project: @project %>
  <% else %>
    <%= render 'applikations/participate_button', user: @user %>
  <% end %>
</div>
<div class="twitter col-xs-12 col-md-4">
  <a href="https://twitter.com/share?ref_src=twsrc%5Etfw" class="twitter-share-button" data-show-count="false" data-text="Matchaでおもしろいプロジェクトを見つけたよ!" data-size="large">Tweet</a>
  <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
  <p class="twitter-share-message">Twitterでシェアしよう!</p>
</div>


<div class="project_tabs col-md-12">
  <ul class="nav nav-tabs nav-justified">
    <li class="nav-item col-xs-4">
      <a class="nav-link active" href="#project_content" data-toggle="tab">活動内容</a>
    </li>
    <li class="nav-item col-xs-4">
      <a class="nav-link" href="#project_participants">参加者 <span class="badge tabs_badge"><%= @not_canceled_participants.length %></span></a>
    </li>
    <li class="nav-item col-xs-4">
      <a class="nav-link" href="#project_comments">コメント <span class="badge tabs_badge"><%= @project.comment_to_projects.count %></span></a>
    </li>
  </ul>
  <div class="tab-content">
    <div id="project_content" class="tab-pane active">
      <p><%= simple_format(text_url_to_link(h(@project.content).html_safe), class:'project_content') %></p>
    </div>
    <div id="project_participants" class="tab-pane">
      <div class="not_canceled_participants">
        <p>参加しているユーザー</p>
        <% if @not_canceled_participants.any? %>
          <%= render 'users/users', users: @not_canceled_participants %>
        <% else %>
          <p class="no_notcanceled_participants">現在このプロジェクトに参加しているユーザーはいません。</p>
        <% end %>
      </div>
      <div class="canceled_participants">
        <p>キャンセルしたユーザー</p>
        <% if @canceled_participants.any? %>
          <%= render 'users/users', users: @canceled_participants %>
        <% else %>
          <p class="no_canceled_participants">現在このプロジェクトへの参加をキャンセルしたユーザーはいません。</p>
        <% end %>
      </div>
    </div>
    <div id="project_comments" class="tab-pane">
      <%= render 'comment_to_projects/comments', comment_to_projects: @project.comment_to_projects %>
      <%= render 'comment_to_projects/form', comment_to_project: @comment_to_project %>
    </div>
  </div>
</div>