config/routes.rb
class AuthenticatedConstraint
  def matches?(request)
    request.session['user_id'].present?
  end
end

Rails.application.routes.draw do
  #mount RailsAdmin::Engine => '/admin', as: 'rails_admin'  　　　devise導入したら使う
  constraints AuthenticatedConstraint.new do
    root to: 'projects#index', as: :user_root
  end
  
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'sample_login', to: 'sessions#sample_login'
  
  get 'signup', to: 'users#new'
  resources :users do
    member do
      get :followings
      get :followers
    end
  end
  
  #get 'projects/category', to: 'projects#category_index'

  #get 'projects/category/language', to: 'projects#category_index'
  #get 'projects/category/club', to: 'projects#category_index'
  #get 'projects/category/event', to: 'projects#category_index'
  #get 'projects/category/study', to: 'projects#category_index'
  #get 'projects/category/job', to: 'projects#category_index'
  #get 'projects/category/debate', to: 'projects#category_index'
  #get 'projects/category/business', to: 'projects#category_index'
  #get 'projects/category/sports', to: 'projects#category_index'
  #get 'projects/category/travel', to: 'projects#category_index'
  #get 'projects/category/hobby', to: 'projects#category_index'
  #get 'projects/category/music', to: 'projects#category_index'
  #get 'projects/category/picture', to: 'projects#category_index'
  #get 'projects/category/art', to: 'projects#category_index'
  #get 'projects/category/game', to: 'projects#category_index'
  #get 'projects/category/technology', to: 'projects#category_index'
  #get 'projects/category/others', to: 'projects#category_index'
  resources :projects, only: [:index, :show, :new, :create, :update] do
    member do
      put :call_off
      resources :comment_to_projects, only: [:index, :create, :edit, :update, :destroy]
    end
    collection do
      get 'all', to: 'projects#all_projects'
      get 'fresh', to: 'projects#fresh_projects'
      get 'popular', to: 'projects#popular_projects'
      get 'closing_soon', to: 'projects#closing_soon_projects'
      get 'category/:id', to: 'projects#category_projects'
      get 'search', to: 'projects#searched_projects'
    end
  end
  resources :user_relationships, only: [:create, :destroy]
  resources :applikations, only: [:create, :update] do
    member do
      put :cancel
      put :rejoin
    end
  end
  resources :project_favorites, only: [:create, :destroy]
end

app/models/comment_to_project.rb
class CommentToProject < ApplicationRecord
  belongs_to :user
  belongs_to :project
  
  validates :comment, presence: true,
                      length: { maximum: 1000 }
end

app/controllers/comment_to_projects_controller.rb
class CommentToProjectsController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only: [:edit, :update, :destroy]

  
  def index
    @comment_to_projects = CommentToProject.all
  end

  def new
    @comment_to_project = CommentToProject.new
  end

  def create
    @project = Project.find(params[:project_id])
    @comment_to_project = @project.comment_to_projects.build(comment_to_project_params)
    @comment_to_project.user_id = current_user.id
    @comment_to_project.project_id = @project.id
    
    if @comment_to_project.save
      flash[:success] = 'コメントを投稿しました。'
      redirect_to "/projects/#{@project.id}"
    else
      flash.now[:danger] = 'コメントの投稿に失敗しました。'
      redirect_back(fallback_location: root_path)
    end
  end

  def edit
  end

  def update
    if @comment_to_project.update(comment_to_project_params)
      flash[:success] = 'コメントを更新しました。'
      redirect_to "/projects/#{@project.id}"
    else
      flash.now[:danger] = 'コメントの更新に失敗しました。'
      redirect_back(fallback_location: root_path)
    end
  end

  def destroy
    @comment_to_project = CommentToProject.find_by(id: params[:id])
    @comment_to_project.destroy
    flash[:success] = 'コメントを削除しました。'
    redirect_back(fallback_location: root_path)
  end
  
  
  
  private
    def comment_to_project_params
      params.require(:comment_to_project).permit(:comment)
    end
    
    def correct_user
      @comment_to_project = current_user.comment_to_projects.find_by(id: params[:id])
      unless @comment_to_project
        redirect_to root_url
      end
    end
end

app/views/comment_to_projects/_comments.html.erb
<% if @project.comment_to_projects.any? %>
  <ul class="media-list">
    <% comment_to_projects.each do |comment_to_project| %>
      <li class="media">
        <a class="media-left" href="#">
          <img class="img-rounded" src="/assets/f_f_object_115_s64_f_object_115_0bg" alt="user_icon_xs">
        </a>
        <div class="media-body">
          <h4 class="comment-heading">
            <%= link_to comment_to_project.user.name, user_path(comment_to_project.user) %>
          </h4>
          <p><%= simple_format(text_url_to_link(h(comment_to_project.comment).html_safe)) %></p>
          <% if current_user == comment_to_project.user %>
            <%= link_to '削除', comment_to_project_path(comment_to_project), method: :delete, data: { confirm: "本当に削除しますか？" }, class: 'btn btn-danger btn-xs' %>
            <%#= link_to '編集', edit_comment_to_project_path(comment_to_project), class: 'btn btn-info btn-xs' %>
          <% end %>
        </div>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/comment_to_projects/_form.html.erb
<%= form_for(@comment_to_project) do |f| %>
  <div class="form-group">
    <%= f.label :comment, 'コメントを投稿' %>
    <%= f.text_area :comment, class: 'form-control', rows: 5 %>
  </div>
  <%= hidden_field_tag :project_id, @project.id %>
  <%= f.submit '投稿する', class: 'btn btn-primary btn-block' %>
<% end %>

app/views/comment_to_projects/edit.html.erb
<h1>CommentToProjects#edit</h1>
<p>Find me in app/views/comment_to_projects/edit.html.erb</p>