config/routes.rb
class AuthenticatedConstraint
  def matches?(request)
    request.session['user_id'].present?
  end
end

Rails.application.routes.draw do
  #mount RailsAdmin::Engine => '/admin', as: 'rails_admin'  　　　devise導入したら使う
  constraints AuthenticatedConstraint.new do
    root to: 'projects#index', as: :user_root
  end
  
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'sample_login', to: 'sessions#sample_login'
  
  get 'signup', to: 'users#new'
  resources :users do
    member do
      get :followings
      get :followers
    end
  end
  
  #get 'projects/category', to: 'projects#category_index'

  #get 'projects/category/language', to: 'projects#category_index'
  #get 'projects/category/club', to: 'projects#category_index'
  #get 'projects/category/event', to: 'projects#category_index'
  #get 'projects/category/study', to: 'projects#category_index'
  #get 'projects/category/job', to: 'projects#category_index'
  #get 'projects/category/debate', to: 'projects#category_index'
  #get 'projects/category/business', to: 'projects#category_index'
  #get 'projects/category/sports', to: 'projects#category_index'
  #get 'projects/category/travel', to: 'projects#category_index'
  #get 'projects/category/hobby', to: 'projects#category_index'
  #get 'projects/category/music', to: 'projects#category_index'
  #get 'projects/category/picture', to: 'projects#category_index'
  #get 'projects/category/art', to: 'projects#category_index'
  #get 'projects/category/game', to: 'projects#category_index'
  #get 'projects/category/technology', to: 'projects#category_index'
  #get 'projects/category/others', to: 'projects#category_index'
  resources :projects, only: [:index, :show, :new, :create, :update] do
    member do
      put :call_off
      resources :comment_to_projects, only: [:index, :create, :edit, :update, :destroy]
    end
    collection do
      get 'all', to: 'projects#all_projects'
      get 'fresh', to: 'projects#fresh_projects'
      get 'popular', to: 'projects#popular_projects'
      get 'closing_soon', to: 'projects#closing_soon_projects'
      get 'category/:id', to: 'projects#category_projects'
      get 'search', to: 'projects#searched_projects'
    end
  end
  resources :user_relationships, only: [:create, :destroy]
  resources :applikations, only: [:create, :update] do
    member do
      put :cancel
      put :rejoin
    end
  end
  resources :project_favorites, only: [:create, :destroy]
end

app/views/layouts/_back_button.html.erb
<div class="col-xs-12">
  <%= link_to '戻る', :back, class: 'back_button label label-default' %>
</div>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<div class="col-xs-12">
  <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <div class="text-center">
      &copy;2019 Masahiro Komori
    </div>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<header>
  <nav class="navbar navbar-inverse navbar-static-top">
    <div class="container">
      <div class="col-xs-12">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-epanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Matcha</a>
        </div>
        <div class="collapse navbar-collapse navbar-right" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <% if logged_in? %>
              <li class="search-nav col-md-2">
                <%= render 'layouts/search' %>
              </li>
              <li><%= link_to 'プロジェクトをはじめる', new_project_path %></li>
              <li class="search_projects">
                <%= link_to 'プロジェクトをさがす', projects_path %>
              </li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.name.truncate(10) %> <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to 'マイページ', user_path(current_user) %></li>
                  <li role="separator" class="driver"></li>
                  <li><%= link_to 'ログアウト', logout_path, method: :delete %></li>
                </ul>
              </li>
            <% else %>
              <li><%= link_to '新規登録', signup_path %></li>
              <li><%= link_to 'ログイン', login_path %></li>
            <% end %>
          </ul>
        </div>
        <ul class="search_projects second-row col-lg-12">
          <li>
            <ul class="project_types">
              <li><%= link_to 'すべてのプロジェクト', all_projects_path %></li>
              <li><%= link_to '新着のプロジェクト', fresh_projects_path %></li>
              <li><%= link_to '人気のプロジェクト', popular_projects_path %></li>
              <li><%= link_to '締切間近のプロジェクト', closing_soon_projects_path %></li>
            </ul>
          </li>
          <li>
            <ul class="project_categories">
              <% project_categories.each do |project_category| %>
                <li><%= link_to project_category.name, "/projects/category/" + project_category.id.to_s %></li>
              <% end %>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/_search.html.erb
<%= search_form_for @search, url: search_projects_path do |f| %>
  <div class="input-group">
    <%= f.text_field :title_or_content_or_project_category_name_cont, placeholder: 'キーワード検索', required: true, class: 'form-control' %>
    <span class="input-group-btn">
      <%= f.submit "検索", class: 'btn btn-default' %>
      <i></i>
    </span>
  </div>
<% end %>

app/views/layouts/_search2.html.erb
<div class="d-flex justify-content-center h-100">
  <div class="searchbar">
    <input class="search_input" type="text" name="" placeholder="Search...">
    <a href="#" class="search_icon"><i class="fas fa-search"></i></a>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <title>Matcha</title>
    <%= csrf_meta_tags %>
    
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Sawarabi+Gothic" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= Gon::Base.render_data %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script>
      (function(a,s,a,y,e,r){
      r=[y];window[a]={r:r};y=document.createElement('script');
      y.src=s;y.async=!!e;y.setAttribute('data-asayer-ns',a);
      document.getElementsByTagName('head')[0].appendChild(y);
      window[a].start=function(v){r.push([0])};
      window[a].vars=function(k,v){r.push([1,k,v])};
      window[a].event=function(t,p){r.push([2,t,p])};
      window[a].id=Function.prototype;
      window[a].started=function(){return false};
      })(0,'https://static.asayer.io/asayer.js','asayer',337,1);
    </script>
  </head>

  <body>
    <%= render 'layouts/navbar', project_categories: @project_categories %>
    
    <div class="container">
      <%= render 'layouts/flash_messages' %>
      
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    
    
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
    <%= javascript_include_tag 'application' %>
  </body>
</html>